# Generated by Django 6.1.1 on 2026-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=50)),
            ],
        ),
    ]
