# Generated by Django 6.1.1 on 2026-09-19 17:51

import django.core.validators
import django.db.models.deletion
import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0002_job_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optionally starting with +).', regex='^\\+?[0-9 ]{7,15}$')])),
                ('ni_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid National Insurance number, e.g. QQ123456C.', regex='^[A-Za-z]{2}[0-9]{6}[A-Za-z]$')])),
                ('address', models.TextField()),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('passport', models.FileField(upload_to='applications/passports/', validators=[user_app.models.validate_passport_size, user_app.models.validate_passport_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_app.job')),
            ],
        ),
    ]
