# Generated by Django 6.1.1 on 2026-09-19 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='zip_code',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zip/postal code.', regex='^[A-Za-z0-9 ]{3,10}$')], verbose_name='Zip code'),
            preserve_default=False,
        ),
    ]
