# Generated by Django 6.1.1 on 2026-09-19 19:29

import django.db.models.deletion
import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been used to apply for a job.'}, max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(max_length=20)),
                ('educational_qualification', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='employees/cv/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension])),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_photo', models.FileField(upload_to='employees/passport_photos/', validators=[user_app.models.validate_document_size, user_app.models.validate_photo_extension], verbose_name='Passport size photo')),
                ('dbs_certificate', models.FileField(upload_to='employees/dbs/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='DBS certificate')),
                ('pcc_certificate', models.FileField(upload_to='employees/pcc/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='PCC certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user_app.application')),
            ],
        ),
    ]
