# Generated by Django 6.1.1 on 2026-09-19 19:45

import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_application_email_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='employees/cv/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dbs_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employees/dbs/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='DBS certificate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='employees/passport_photos/', validators=[user_app.models.validate_document_size, user_app.models.validate_photo_extension], verbose_name='Passport size photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pcc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employees/pcc/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='PCC certificate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='share_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
