# Generated by Django 6.1.1 on 2026-09-28 10:34

import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_employee_cv_alter_employee_dbs_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_documents',
            field=models.FileField(blank=True, null=True, upload_to='employees/extra_documents/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='Extra documents'),
        ),
        migrations.AddField(
            model_name='employee',
            name='right_to_work',
            field=models.FileField(blank=True, null=True, upload_to='employees/right_to_work/', validators=[user_app.models.validate_document_size, user_app.models.validate_document_extension], verbose_name='Right to work'),
        ),
    ]
