# Generated by Django 6.1.1 on 2026-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_job_slug_unique'),
        ('user_app', '0006_employee_extra_documents_employee_right_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'email'), name='unique_application_job_email'),
        ),
    ]
